### ISSUE TITLE
Add myChapman to 'login' menu

### ISSUE THREAD

**Issue by megagie** [chapmanu/omni-nav#15]
move MyWindow to the “faculty and staff” page and add MyChapman (https://my.chapman.edu) so the drop down would read:

· Blackboard
· WebAdvisor
· Faculty and Staff Email
· Panther Mail
· MyChapman

WebAdvisor will eventually be  replaced by MyChapman, but it’s not yet.

**Comment by bcole808** [comment]
For clarification, these are the tasks I am about to do:

1. Remove "My Window"
2. Remove "OrgSync"
3. Change order of Staff and Student email links
4. Add "MyChapman" to bottom of list.

**Comment by bcole808** [comment]
Note: Blogs and Inside/Social/Events are deployed and live. Cascade will be updated on the next sitewide republish.
