### ISSUE TITLE
Follow or update .editorconfig?

### ISSUE THREAD

**Issue by jonathantneal** [chapmanu/omni-nav#32]
You’re using an EditorConfig file — [.editorconfig](https://github.com/chapmanu/omni-nav/blob/omninav-as-a-service/.editorconfig) — but I notice some files aren’t following it.

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. http://editorconfig.org/

Currently, I’m seeing mixed indentation, like tabs used on one line and then spaces for another. Right now, you’re set to use tabs. https://github.com/jonathantneal/omni-nav/blob/development/.editorconfig#L3

Many editors come bundled with native support for EditorConfig, but others may need to install a plugin. Any editor you use should be covered here. http://editorconfig.org/#download

Keep on being awesome!

**Comment by kaylaziegler** [comment]
@jonathantneal Thank you for bringing that up. I just jumped into this project for the first time on Friday and wasn't looking at that file. I'll be updating the default config to match our current best practices and trying to fix the files that don't currently follow them.
