### ISSUE TITLE
z-index is not high enough for ChapmanU home page

### ISSUE THREAD

**Issue by bcole808** [chapmanu/omni-nav#6]
![screen shot 2014-10-08 at 4 09 58 pm](https://cloud.githubusercontent.com/assets/5074711/4568872/47cb2c78-4f40-11e4-9ddc-46a9d4a2bb68.png)

**Comment by kaylaziegler** [comment]
This is a really old version of the OmniNav. Issue is no longer relevant.

**Comment by jonathantneal** [comment]
![happy old man](https://vignette.wikia.nocookie.net/trollpasta/images/1/18/Happy-old-man.jpg)

**Comment by tatwell** [comment]
@kaylaziegler On the subject of z-indexes, this reminds me to share this with you:

- https://news.ycombinator.com/item?id=16353121

**Comment by kaylaziegler** [comment]
@tatwell Thanks for that Tom! I just recently updated our documentation with some z-index best practices, hoping we can kind of keep them under control.
